services:
  virtual_postgres:
    container_name: postgres_docker
    image: postgres:16
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata_docker:/var/lib/postgresql/data
    networks:
      - hardcodelabsnet

  redis:
    container_name: redis_docker
    image: redis:latest
    restart: always
    env_file:
      - .env
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    networks:
      - hardcodelabsnet

networks:
  hardcodelabsnet:
    driver: bridge

volumes:
  pgdata_docker:
    driver: local
  redisdata:
    driver: local
