services:
  expsysapp:
    image: hardcodelabs/hardcodelabs:expsys-0.0.2
    container_name: expsysdev
    restart: always
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - hardcodelabsnet
    depends_on:
      - virtual_postgres
